name: Bug Report
description: Report a bug with LibAnimate
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Numbered steps to trigger the bug
      placeholder: |
        1. Call `lib:Animate(frame, "fadeIn", { ... })`
        2. Immediately call `lib:Stop(frame)`
        3. Observe error in chat
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happens (include errors)
    validations:
      required: true
  - type: dropdown
    id: wow-version
    attributes:
      label: WoW Version
      description: Which version of World of Warcraft are you playing?
      options:
        - Retail
        - TBC Anniversary
        - MoP Classic
    validations:
      required: true
  - type: input
    id: lib-animate-version
    attributes:
      label: LibAnimate Version
      description: 'Version number or "latest"'
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Screenshots, error logs, addon list
    validations:
      required: false
