name: Feature Request
description: Suggest a new feature or improvement for LibAnimate
title: "[Feature]: "
labels:
  - enhancement
assignees: []
body:
  - type: textarea
    id: problem-motivation
    attributes:
      label: Problem / Motivation
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the desired feature or API
    validations:
      required: true
  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: Other approaches you've considered
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Examples, references, mockups
    validations:
      required: false
